[package]
name = "extract_pdb_find_to_db"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.11"
pdb = "0.8.0"
sqlx = "0.8.3"
sqlx-cli = "0.8.3"
symbolic-common = "12.14.1"
symbolic-demangle = "12.14.1"
tokio = "1.44.1"
